// src/components/Routes.svelte
<script lang="ts">
  import { Route } from 'svelte-routing'

  import * as Dev from './Dev'
  import Home from './Home.svelte'
  import * as Properties from './Properties'
  import Search from './Search'
  import * as Spaces from './Spaces'
  import * as Traits from './Traits'
  import * as Theorems from './Theorems'
</script>

<Route path="/spaces" component={Search} />
<Route path="/spaces/:spaceId/properties/:propertyId" component={Traits.Show} />
<Route path="/spaces/:id/*" component={Spaces.Show} />
<Route path="/properties" component={Properties.List} />
<Route path="/properties/:id/*" component={Properties.Show} />
<Route path="/theorems" component={Theorems.List} />
<Route path="/theorems/:id/*" component={Theorems.Show} />
<Route path="/dev" component={Dev.Settings} />
<Route path="/dev/preview" component={Dev.Preview} />
<Route path="/" component={Home} />

// src/routes/index.jsx
import React from 'react'
import Relay from 'react-relay'
import {Route} from 'react-router'

import App    from '../components/App'
import Space  from '../components/Space'
import Spaces from '../components/Spaces'
import Search from '../components/Search'
import Trait  from '../components/Trait'

const SpaceQueries = {
  space: () => Relay.QL`query { space(id: $spaceId) }`
}
const ViewerQueries = {
  viewer: () => Relay.QL`query { viewer }`
}

const routes = <Route path="/" component={App}>
  <Route path="spaces" component={Spaces} queries={ViewerQueries}/>
  <Route path="spaces/:spaceId" component={Space} queries={SpaceQueries}>
    <Route path="properties/:propertyId" component={Trait} queries={SpaceQueries}/>
  </Route>
  <Route path="search" component={Search}/>
</Route>

export default routes
