// src/components/Shared/Formula.tsx
import React from 'react'
import { Link } from 'react-router-dom'

import { formula as F } from '@pi-base/core'

import { Property, Store, useStore } from '../../models'
import paths from '../../paths'
import { Title } from './Display'

function intersperse(list: JSX.Element[], sep: string) {
  const result: JSX.Element[] = []
  for (let i = 0; i < list.length; i++) {
    result[2 * i] = list[i]
    result[2 * i - 1] = <span key={2 * i - 1}>{` ${sep} `}</span>
  }
  return result
}

function render<P>(
  element: (p: P) => JSX.Element,
  formula: F.Formula<P>
): JSX.Element {
  switch (formula.kind) {
    case 'and':
      return (
        <>
          {'('}
          {
            intersperse(
              formula.subs.map(
                sf => render(element, sf)
              ),
              'Λ'
            )
          }
          {')'}
        </>
      )
    case 'or':
      return (
        <>
          {'('}
          {
            intersperse(
              formula.subs.map(
                sf => render(element, sf)
              ),
              '∨'
            )
          }
          {')'}
        </>
      )
    case 'atom':
      if (formula.value === false) {
        return (
          <>¬{element(formula.property)}</>
        )
      } else {
        return element(formula.property)
      }
  }
}

export function Display({
  value,
  link = "none"
}: {
  value: F.Formula<Property>
  link?: "property" | "none"
}) {
  const format = link === "property"
    ? (p: Property) => <Link key={p.uid} to={paths.property(p)}><Title body={p.name}></Title></Link>
    : (p: Property) => <Title key={p.uid} body={p.name} />

  return (<>{render(format, value)}</>)
}

export default function ({
  value,
  link = "none"
}: {
  value: F.Formula<string>
  link?: "property" | "none"
}) {
  const store = useStore()
  const resolved = F.mapProperty((id: string) => Store.property(store, id)!, value)

  return (<Display value={resolved} link={link} />)
}

// src/components/Shared/Formula.svelte
<script lang="ts">
  import { Link } from 'svelte-routing'
  import type * as F from '@pi-base/core/lib/Formula'
  import Typeset from './Typeset.svelte'
  import type { Property } from '../../types'

  export let value: F.Formula<Property>
</script>

{#if value.kind === 'atom'}
  {value.value ? '' : '¬'}
  <Link to="/properties/{value.property.uid}">
    <Typeset body={value.property.name} />
  </Link>
{:else if value.kind === 'and'}
  {#each value.subs as f, i}
    <svelte:self value={f} />
    {i === value.subs.length - 1 ? '' : '∧'}
  {/each}
{:else}
  {#each value.subs as f, i}
    <svelte:self value={f} />
    {i === value.subs.length - 1 ? '' : '∨'}
  {/each}
{/if}
