// src/components/Shared/FormulaInput/Suggestions.svelte
<script lang="ts">
  import { Tex } from '../../Shared'

  export let apply: (index: number) => void
  export let selected: number | null = null
  export let suggestions: string[]
</script>

{#if suggestions.length > 0}
  <div class="suggestions list-group">
    {#each suggestions as suggestion, index (suggestion)}
      <button
        class="list-group-item list-group-item-action"
        class:active={index === selected}
        on:click={() => apply(index)}
      >
        <Tex body={suggestion} />
      </button>
    {/each}
  </div>
{/if}

// src/components/Shared/FormulaInput/Suggestions.tsx
import React from 'react'
import { ListGroup } from 'react-bootstrap'

import Inline from '../Inline'

export default function Suggestions({
  apply,
  selected,
  suggestions
}: {
  apply: (index: number) => void
  selected: number | null,
  suggestions: readonly string[]
}) {
  return (
    <ListGroup>
      {suggestions.map((suggestion: string, index: number) =>
        <ListGroup.Item
          key={suggestion}
          active={index === selected}
          onClick={() => apply(index)}
          action
        >
          <Inline body={suggestion} />
        </ListGroup.Item>
      )}
    </ListGroup>
  )
}
