// src/components/Properties/Detail.tsx
import React from 'react'

import { Property } from '../../models'
import Display from '../Shared/Display'
import Refs from '../Shared/Refs'
import { Tab, Tabs } from '../Shared/RouteTabs'
import Title from '../Shared/Title'
import Traits from './Traits'
import Theorems from './Theorems'

export default React.memo(
  function Detail({ property }: { property: Property }) {
    return (
      <>
        <Title title={property.name} aliases={property.aliases} />
        <Display body={property.description} />
        <Tabs initial="theorems">
          <Tab eventKey="theorems" title="Theorems">
            <Theorems property={property} />
          </Tab>
          <Tab eventKey="spaces" title="Spaces">
            <Traits property={property} />
          </Tab>
          <Tab eventKey="references" title="References">
            <Refs refs={property.refs} />
          </Tab>
        </Tabs>
      </>
    )
  }
)

// src/components/Properties/Detail.svelte
<script lang="ts">
  import { Property } from '../../models'
  import * as paths from '../../paths'
  import { Aliases, References, Tab, Tabs, Tex } from '../Shared'
  import Theorems from './Theorems.svelte'
  import Traits from './Traits.svelte'

  export let property: Property
  export let tab: 'theorems' | 'spaces' | 'references' = 'theorems'
</script>

<h1>
  <Tex body={property.name} />
  {#if property.aliases}
    <Aliases names={property.aliases} />
  {/if}
</h1>

<Tex body={property.description} />
<p />

<Tabs root={paths.property(property)} selected={tab} let:tabs>
  <Tab {tabs} path="theorems"><Theorems {property} /></Tab>
  <Tab {tabs} path="spaces"><Traits {property} /></Tab>
  <Tab {tabs} path="references"><References refs={property.refs} /></Tab>
</Tabs>
