// src/components/Properties/List.tsx
import React from 'react'
import { Link } from 'react-router-dom'

import { Property } from '../../models'
import paths from '../../paths'
import Filter, { useFilter } from '../Shared/Filter'
import { Preview, Title } from '../Shared/Display'
import Id from '../Shared/Id'
import Table from '../Shared/Table'

const Header = () =>
  <tr>
    <Table.Header sort="uid">Id</Table.Header>
    <Table.Header sort="name">Name</Table.Header>
    <Table.Header>Description</Table.Header>
  </tr>

const Row = ({ item: property }: { item: Property }) =>
  <tr>
    <td>
      <Link to={paths.property(property)}>
        <Id value={property.uid} />
      </Link>
    </td>
    <td>
      <Title body={property.name} />
    </td>
    <td>
      <Preview body={property.description} />
    </td>
  </tr>

export default React.memo(
  function PropertiesList({ properties }: { properties: Property[] }) {
    const {
      filtered,
      setFilter
    } = useFilter(properties)

    return (
      <>
        <Filter onChange={setFilter} />
        <Table
          Header={Header}
          Row={Row}
          collection={filtered}
        />
      </>
    )
  }
)

// src/components/Properties/List.svelte
<script lang="ts">
  import { Property } from '../../models'
  import { Filtered, Id, Preview, Table, Tex } from '../Shared'

  export let properties: Property[]
</script>

<Filtered
  collection={properties}
  weights={{
    name: 0.7,
    aliases: 0.5,
    description: 0.2,
  }}
  let:filtered
>
  <Table collection={filtered} key={(t) => t.uid}>
    <tr slot="header" let:sort>
      <th on:click={sort('uid')}>Id</th>
      <th on:click={sort('name')}>Name</th>
      <th>Description</th>
    </tr>

    <tr slot="row" let:object={property}>
      <td><Id value={property.uid} /></td>
      <td><Tex body={property.name} /></td>
      <td><Preview body={property.description} /></td>
    </tr>
  </Table>
</Filtered>
