// src/components/Properties/Theorems.tsx
import React from 'react'

import { Property, useStore } from '../../models'
import { theoremsWithProperty } from '../../models/Store'
import Theorems from '../Theorems/SummaryList.svelte'
import { Svelte } from '../Svelte'

export default function ({ property }: { property: Property }) {
  const store = useStore()
  const theorems = theoremsWithProperty(store, property)

  return <Svelte component={Theorems} props={{ theorems }} />
}

// src/components/Properties/Theorems.svelte
<script lang="ts">
  import { Property } from '../../models'
  import { theoremsWithProperty } from '../../models/Store'
  import Theorems from '../Theorems/SummaryList.svelte'
  import { getStore } from '../Svelte'

  export let property: Property

  $: theorems = theoremsWithProperty(getStore(), property)
</script>

<Theorems {theorems} />
