// src/components/Traits/Detail.svelte
<script lang="ts">
  import { Link } from 'svelte-routing'
  import type { Property, Space, Trait } from '../../models'
  import paths from '../../paths'
  import { References, Tex } from '../Shared'
  import Proof from './Proof.svelte'

  export let property: Property
  export let space: Space
  export let trait: Trait
</script>

<h1>
  <Link to={paths.space(space)}>
    <Tex body={space.name} />
  </Link>
  {trait.value ? 'is' : 'is not'}
  <Link to={paths.property(property)}>
    <Tex body={property.name} />
  </Link>
</h1>

{#if trait.proof}
  <Proof {space} proof={trait.proof} />
{:else}
  <Tex body={trait.description} />
  <p />
  <h4>References</h4>
  <References refs={trait.refs} />
{/if}

// src/components/Traits/Detail.tsx
import React from 'react'
import { Link } from 'react-router-dom'

import { Property, Space, Trait } from '../../models'
import paths from '../../paths'
import Description from '../Shared/Description'
import Inline from '../Shared/Inline'
import Proof from './Proof'

export default React.memo(
  function Detail({ property, space, trait }: {
    property: Property
    space: Space
    trait: Trait
  }) {
    return (
      <>
        <h1>
          <Link to={paths.space(space)}>
            <Inline body={space.name} />
          </Link>
          {trait.value
            ? ' is '
            : ' is not '}
          <Link to={paths.property(property)}>
            <Inline body={property.name} />
          </Link>
        </h1>

        {trait.proof
          ? <Proof space={space} proof={trait.proof} />
          : <Description body={trait.description} refs={trait.refs} />
        }
      </>
    )
  }
)
