// src/components/Traits/Proof.tsx
import React from 'react'
import { Col, Row } from 'react-bootstrap'

import { Space, useStore } from '../../models'
import { Proof, default as S } from '../../models/Store'
import Theorems from '../Theorems/SummaryList.svelte'
import Traits from '../Spaces/TraitsForProperties.svelte'
import { Svelte } from '../Svelte'

export default function ({ space, proof }: { space: Space; proof: Proof }) {
  const store = useStore()

  const theorems = proof.theorems.map((id: string) => S.theorem(store, id)!)
  const properties = proof.properties.map(
    (id: string) => S.property(store, id)!
  )

  return (
    <>
      <p>Automatically deduced from the following</p>
      <Row>
        <Col xs="6">
          <h5>Properties</h5>
          <Svelte component={Traits} props={{ space, properties }} />
        </Col>
        <Col xs="6">
          <h5>Theorems</h5>
          <Svelte component={Theorems} props={{ theorems }} />
        </Col>
      </Row>
    </>
  )
}

// src/components/Traits/Proof.svelte
<script lang="ts">
  import { Space } from '../../models'
  import { Proof, default as S } from '../../models/Store'
  import Theorems from '../Theorems/SummaryList.svelte'
  import Traits from '../Spaces/TraitsForProperties.svelte'
  import { getStore } from '../Svelte'

  export let space: Space
  export let proof: Proof

  const store = getStore()

  $: theorems = proof.theorems.map((id: string) => S.theorem(store, id)!)
  $: properties = proof.properties.map((id: string) => S.property(store, id)!)
</script>

<p>Automatically deduced from the following</p>
<div class="row">
  <div class="col-6">
    <h5>Properties</h5>
    <Traits {space} {properties} />
  </div>
  <div class="col-6">
    <h5>Theorems</h5>
    <Theorems {theorems} />
  </div>
</div>
