// src/components/Proof.jsx
import React, { PropTypes } from 'react'
import { connect } from 'react-redux'
import { Link } from 'react-router'

import * as Q from '../queries'

import Markdown    from './Markdown'
import Implication from './Implication'

class Explorer extends React.Component {
  render() {
    const { space, proof } = this.props

    if (!proof) { return null }

    return <div className="proofExplorer">
      <p>Automatically deduced from the following properties</p>
      <ul>
        {proof.traits.map(t =>
          <li key={'prop' + t.property.uid}>
            <Link to={`/spaces/${space.name}/properties/${t.property.name}`}>
              {t.value ? '' : '¬'}
              {t.property.name}
            </Link>
          </li>
        )}
      </ul>

      <p>and theorems</p>
      <ul>
        {proof.theorems.map(t =>
          <li key={'implication' + t.uid}>
            <Link to={`/theorems/${t.uid}`}>
              <Implication theorem={t} link={false}/>
            </Link>
          </li>
        )}
      </ul>
    </div>
  }
}

Explorer.propTypes = {
  space: PropTypes.object.isRequired,
  trait: PropTypes.object.isRequired
}

const ProofExplorer = connect(
  (state, ownProps) => ({
    proof: Q.getProof(state, ownProps.trait)
  })
)(Explorer)

class Proof extends React.Component {
  render() {
    const { space, trait } = this.props

    if (trait.deduced) {
      return <ProofExplorer space={space} trait={trait}/>
    } else if (trait.description) {
      return <Markdown text={trait.description}/>
    } else {
      return <p>
        <i>No proof given</i>
      </p>
    }
  }
}

export default Proof

// src/components/Traits/Proof.svelte
<script lang="ts">
  import { Formula, Id, Link } from '../Shared'
  import Value from './Value.svelte'
  import type { Space, Theorem } from '../../models'

  export let space: Space
  export let traits: {
    pid: string
    name: string
    value: boolean
    deduced: boolean
  }[]
  export let theorems: Theorem[]
</script>

Automatically deduced from the following
<div class="row">
  <div class="col">
    <h5>Properties</h5>
    <table class="table">
      <thead>
        <tr>
          <th>Property</th>
          <th>Value</th>
          <th>Deduced</th>
        </tr>
      </thead>
      <tbody>
        {#each traits as { pid, name, value, deduced } (pid)}
          <tr>
            <td>
              <Link to="/properties/{pid}">{name}</Link>
            </td>
            <td>
              <Link to="/spaces/{space.uid}/properties/{pid}">
                <Value {value} />
              </Link>
            </td>
            <td>
              {#if deduced}
                <Value value={true} />
              {/if}
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
  <div class="col">
    <h5>Theorems</h5>
    <table class="table">
      <thead>
        <tr>
          <th>Id</th>
          <th>When</th>
          <th>Then</th>
        </tr>
      </thead>
      <tbody>
        {#each theorems as { uid, when, then } (uid)}
          <tr>
            <td>
              <Link to="/theorems/{uid}">
                <Id {uid} />
              </Link>
            </td>
            <td>
              <Formula value={when} />
            </td>
            <td>
              <Formula value={then} />
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
</div>
