// src/components/Proof/index.tsx
import * as React from 'react'
import { connect } from 'react-redux'
import { Link } from 'react-router-dom'

import * as S from '../../selectors'
import { Proof, State, Trait } from '../../types'

import Implication from '../Implication'
import Markdown from '../Markdown'
import Tex from '../Tex'

type OwnProps = {
  trait: Trait
}
type StateProps = {
  proof: Proof | undefined
}
type Props = OwnProps & StateProps

function Proof({ trait, proof }: Props) {
  if (proof) {
    return (
      <div className="proofExplorer">
        <p>Automatically deduced from the following properties</p>
        <ul>
          {proof.traits.map(t => (
            <li key={`prop${t.property.uid}`}>
              <Link to={`/spaces/${trait.space.uid}/properties/${t.property.uid}`}>
                {t.value ? '' : '¬'}
                <Tex component="span">{t.property.name}</Tex>
              </Link>
            </li>
          ))}
        </ul>

        <p>and theorems</p>
        <ul>
          {proof.theorems.map(t => (
            <li key={`implication${t.uid}`}>
              <Link to={`/theorems/${t.uid}`}>
                <Implication theorem={t} link={false} />
              </Link>
            </li>
          ))}
        </ul>
      </div>
    )
  } else if (trait.description) {
    return <Tex><Markdown text={trait.description} /></Tex>
  } else {
    return (
      <p>
        <i>No proof given</i>
      </p>
    )
  }
}

export default connect<StateProps, {}, OwnProps>(
  (state: State, ownProps: OwnProps): StateProps => ({
    proof: S.proof(state, ownProps.trait.space.uid, ownProps.trait.property.uid)
  })
)(Proof)

// src/components/Traits/Proof.svelte
<script lang="ts">
  import { Formula, Id, Link } from '../Shared'
  import Value from './Value.svelte'
  import type { Space, Theorem } from '../../models'

  export let space: Space
  export let traits: {
    pid: string
    name: string
    value: boolean
    deduced: boolean
  }[]
  export let theorems: Theorem[]
</script>

Automatically deduced from the following
<div class="row">
  <div class="col">
    <h5>Properties</h5>
    <table class="table">
      <thead>
        <tr>
          <th>Property</th>
          <th>Value</th>
          <th>Deduced</th>
        </tr>
      </thead>
      <tbody>
        {#each traits as { pid, name, value, deduced } (pid)}
          <tr>
            <td>
              <Link to="/properties/{pid}">{name}</Link>
            </td>
            <td>
              <Link to="/spaces/{space.uid}/properties/{pid}">
                <Value {value} />
              </Link>
            </td>
            <td>
              {#if deduced}
                <Value value={true} />
              {/if}
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
  <div class="col">
    <h5>Theorems</h5>
    <table class="table">
      <thead>
        <tr>
          <th>Id</th>
          <th>When</th>
          <th>Then</th>
        </tr>
      </thead>
      <tbody>
        {#each theorems as { uid, when, then } (uid)}
          <tr>
            <td>
              <Link to="/theorems/{uid}">
                <Id {uid} />
              </Link>
            </td>
            <td>
              <Formula value={when} />
            </td>
            <td>
              <Formula value={then} />
            </td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
</div>
