// src/components/Trait/Table.jsx
import React from 'react'
import { connect } from 'react-redux'
import { Link } from 'react-router'

import * as Q from '../../queries'

import Icon from '../Icon'
import Tex  from '../Tex'

class TraitTable extends React.Component {
  check(traits, space, property) {
    const val = traits.getIn([space.uid, property.uid, 'value'])
    let type
    if (val === true) {
      type = "ok"
    } else if (val === false) {
      type = "remove"
    } else {
      type = "question-sign"
    }

    return (
      <Link to={`/spaces/${space.name}/properties/${property.name}`}>
        <Icon type={type}/>
      </Link>
    )
  }
  render() {
    const { spaces, properties, traits } = this.props

    return (
      <table className="table table-condensed table-striped table-hover">
        <thead>
          <tr>
            <td></td>
            {properties.map(p =>
              <td key={p.uid}>
                <Link to={`/properties/${p.name}`}>
                  <Tex>{p.name}</Tex>
                </Link>
              </td>
            )}
          </tr>
        </thead>
        <tbody>
          {spaces.map(s =>
            <tr key={s.uid}>
              <td>
                <Link to={`/spaces/${s.name}`}>
                  <Tex>{s.name}</Tex>
                </Link>
              </td>
              {properties.map(p =>
                <td key={p.uid}>{this.check(traits, s, p)}</td>
              )}
            </tr>
          )}
        </tbody>
      </table>
    )
  }
}

export default connect(
  (state, ownProps) => ({
    traits: Q.traitTable(state, ownProps.spaces, ownProps.properties)
  })
)(TraitTable)

// src/components/Traits/Table.svelte
<script lang="ts">
  import context from '../../context'
  import type { Property, Space } from '../../models'

  import { Link, Typeset } from '../Shared'
  import Value from './Value.svelte'

  export let properties: Property[]
  export let spaces: Space[]

  const { traits } = context()
</script>

<table class="table">
  <thead>
    <tr>
      <td />
      {#each properties as { uid, name } (uid)}
        <td>
          <Link to="/properties/{uid}">
            <Typeset body={name} />
          </Link>
        </td>
      {/each}
    </tr>
  </thead>
  <tbody>
    {#each spaces as space (space.uid)}
      <tr>
        <td>
          <Link to="/spaces/{space.uid}">
            <Typeset body={space.name} />
          </Link>
        </td>
        {#each properties as property (property.uid)}
          <td>
            <Link to="/spaces/{space.uid}/properties/{property.uid}">
              <Value value={$traits.find(space, property)?.value} />
            </Link>
          </td>
        {/each}
      </tr>
    {/each}
  </tbody>
</table>
