// src/components/Trait/Table.tsx
import * as React from 'react'
import { Link } from 'react-router'
import * as I from 'immutable'

import store from '../../store'
import * as T from '../../types'

import Icon from '../Icon'
import Tex from '../Tex'

export interface Props {
  spaces: I.List<T.Space>
  properties: I.List<T.Property>
  // traits: T.TraitTable
}

function check(space: T.Space, property: T.Property) {
  const val = store.traits.check(space.uid, property.uid)
  let type
  if (val === true) {
    type = 'ok'
  } else if (val === false) {
    type = 'remove'
  } else {
    type = 'question-sign'
  }

  return (
    <Link to={`/spaces/${space.uid}/properties/${property.uid}`}>
      <Icon type={type} />
    </Link>
  )
}

function TraitTable({ spaces, properties }: Props) {
  return (
    <table className="table table-condensed table-striped table-hover">
      <thead>
        <tr>
          <th>Space</th>
          {properties.map((p: T.Property) => (
            <th key={p.uid}>
              <Link to={`/properties/${p.uid}`}>
                <Tex>{p.name}</Tex>
              </Link>
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {spaces.map((s: T.Space) => (
          <tr key={s.uid}>
            <td>
              <Link to={`/spaces/${s.uid}`}>
                <Tex>{s.name}</Tex>
              </Link>
            </td>
            {properties.map((p: T.Property) => (
              <td key={p.uid}>{check(s, p)}</td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  )
}

export default TraitTable

// src/components/Traits/Table.svelte
<script lang="ts">
  import context from '../../context'
  import type { Property, Space } from '../../types'

  import { Link, Typeset } from '../Shared'
  import Value from './Value.svelte'

  export let properties: Property[]
  export let spaces: Space[]

  const { traits } = context()
</script>

<table class="table">
  <thead>
    <tr>
      <td />
      {#each properties as { uid, name } (uid)}
        <td>
          <Link to="/properties/{uid}">
            <Typeset body={name} />
          </Link>
        </td>
      {/each}
    </tr>
  </thead>
  <tbody>
    {#each spaces as space (space.uid)}
      <tr>
        <td>
          <Link to="/spaces/{space.uid}">
            <Typeset body={space.name} />
          </Link>
        </td>
        {#each properties as property (property.uid)}
          <td>
            <Link to="/spaces/{space.uid}/properties/{property.uid}">
              <Value value={$traits.find(space, property)?.value} />
            </Link>
          </td>
        {/each}
      </tr>
    {/each}
  </tbody>
</table>
