// src/components/Shared/NotFound.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import context from '../../context'

  const { errorHandler } = context()

  let location: Location = window.location

  onMount(() => {
    location = window.location

    errorHandler(new Error('Not Found'), { location })
  })
</script>

<div class="wide jumbotron">
  <div class="container">
    <h1><code>404</code> Not Found</h1>
    <p>
      You appear to be looking for
      {' '}
      <code>{location.pathname}</code>, but no matching page was found.
    </p>
    <p>
      If this is a bug, please help out by
      <a
        href="https://github.com/pi-base/viewer/issues/new?title=Could not find {location.pathname + location.search}&body=If possible, add a description of how you got to this page, and what you'd expect to find here.">
        reporting it
      </a>.
    </p>
  </div>
</div>

// src/components/NotFound.jsx
import React from 'react'
import { connect } from 'react-redux'

import * as A from '../actions'

class NotFound extends React.Component {
  render() {
    const path = this.props.router.location.pathname

    this.props.report(path)

    return <div className="jumbotron">
      <h1>404: Page Not Found</h1>
      <p>You appear to be looking for <code>{path}</code>, but we don't know how to find that.</p>
      <p>
        You can press the back button to head back where you were, or
        {' '}
        <a href="https://github.com/jamesdabbs/pi-base-viewer/issues">report this</a>
        {' '}
        if you think it's a bug.
        </p>
    </div>
  }
}

export default connect(
  (state) => ({}),
  (dispatch) => ({
    report: (path) => dispatch(A.pageNotFound(path))
  })
)(NotFound)
