// src/components/Preview.tsx
import React, { useState } from 'react'
import { Col, Form, Row } from 'react-bootstrap'

import Display from './Shared/Display'

export default function Preview() {
  const [body, setBody] = useState('')

  return (
    <Row>
      <Col xs="6">
        <Form.Control
          as="textarea"
          rows={10}
          value={body}
          placeholder="Enter text to preview"
          onChange={e => setBody(e.target.value)}
        />
      </Col>
      <Col xs="6">
        <Display body={body} />
      </Col>
    </Row>
  )
}

// src/components/Preview.svelte
<script lang="ts">
  import { Tex } from './Shared/index'

  let body = ''
</script>

<div class="row">
  <div class="col-6">
    <textarea
      bind:value={body}
      class="form-control"
      rows={10}
      placeholder="Enter text to preview"
    />
  </div>
  <div class="col-6">
    <!-- FIXME: this component currently only renders on mount -->
    <Tex {body} />
  </div>
</div>
