// src/components/Properties/Detail.svelte
<script lang="ts">
  import { Property } from '../../models'
  import * as paths from '../../paths'
  import { References, Tab, Tabs, Tex, Title } from '../Shared'
  import Theorems from './Theorems.svelte'
  import Traits from './Traits.svelte'

  export let property: Property
  export let tab: 'theorems' | 'spaces' | 'references' = 'theorems'
</script>

<Title {...property} />

<Tex body={property.description} />
<p />

<Tabs root={paths.property(property)} selected={tab} let:tabs>
  <Tab {tabs} path="theorems"><Theorems {property} /></Tab>
  <Tab {tabs} path="spaces"><Traits {property} /></Tab>
  <Tab {tabs} path="references"><References refs={property.refs} /></Tab>
</Tabs>

// src/components/Theorems/Detail.tsx
import React from 'react'

import { Theorem } from '../../models'
import Converse from './Converse'
import Display from '../Shared/Display'
import Name from './Name'
import Refs from '../Shared/Refs'
import { Tab, Tabs } from '../Shared/RouteTabs'

export default React.memo(
  function Detail({ theorem }: { theorem: Theorem }) {
    return (
      <>
        <h1>
          <Name theorem={theorem} link='property' />
        </h1>
        <Display body={theorem.description} />
        <Tabs initial="converse">
          <Tab eventKey="converse" title="Converse">
            <Converse theorem={theorem} />
          </Tab>
          <Tab eventKey="references" title="References">
            <Refs refs={theorem.refs} />
          </Tab>
        </Tabs>
      </>
    )
  }
)
