// src/components/Theorems/Detail.svelte
<script lang="ts">
  import { Theorem } from '../../models'
  import { Tabs, Tab } from '../Shared/Tabs'
  import Formula from '../Shared/Formula.svelte'
  import Tex from '../Shared/Tex.svelte'
  import * as paths from '../../paths'
  import Converse from './Converse.svelte'
  import References from '../Shared/References.svelte'

  export let theorem: Theorem
  export let tab: 'converse' | 'references' = 'converse'
</script>

<h1>
  <Formula value={theorem.when} />
  ⇒
  <Formula value={theorem.then} />
</h1>

<Tex body={theorem.description} />
<p />

<Tabs root={paths.theorem(theorem)} selected={tab} let:tabs>
  <Tab {tabs} path="converse"><Converse {theorem} /></Tab>
  <Tab {tabs} path="references"><References refs={theorem.refs} /></Tab>
</Tabs>

// src/components/Theorems/Detail.tsx
import React from 'react'

import { Theorem } from '../../models'
import Converse from './Converse'
import Display from '../Shared/Display'
import Name from './Name'
import Refs from '../Shared/Refs'
import { Tab, Tabs } from '../Shared/RouteTabs'

export default React.memo(
  function Detail({ theorem }: { theorem: Theorem }) {
    return (
      <>
        <h1>
          <Name theorem={theorem} link='property' />
        </h1>
        <Display body={theorem.description} />
        <Tabs initial="converse">
          <Tab eventKey="converse" title="Converse">
            <Converse theorem={theorem} />
          </Tab>
          <Tab eventKey="references" title="References">
            <Refs refs={theorem.refs} />
          </Tab>
        </Tabs>
      </>
    )
  }
)
