// src/components/Shared/Formula/Input/Suggestions.svelte
<script lang="ts">
  import type { Property } from '../../../../models'
  import Typeset from '../../Typeset.svelte'

  export let suggestions: Property[]
  export let selected: number | undefined
  export let onHover: (index: number) => void
  export let onClick: (index: number) => void
</script>

<ul class="list-group">
  {#each suggestions as property, i (property.id)}
    <li
      class="list-group-item {i === selected ? 'active' : ''}"
      on:mouseover={() => onHover(i)}
      on:click={() => onClick(i)}>
      <Typeset body={property.name} />
    </li>
  {/each}
</ul>

// src/components/Formula/Suggestions.tsx
import * as React from 'react'
import * as I from 'immutable'

import * as T from '../../types'

export interface Props {
  suggestions: I.List<T.Property>
  selected:    number
  visible:     boolean
  onSelect:    (selected: number) => void
}

function Suggestions({ suggestions, selected, visible, onSelect }: Props) {
  const divStyle = {
    display:   (visible ? 'block' : 'none'),
    marginTop: '5px'
  }

  return (
    <div className="list-group" style={divStyle}>
      {suggestions.map((p, i) => (
        <a
          className={'list-group-item ' + (selected === i ? 'active' : '')}
          key={p!.uid}
          onMouseDown={() => onSelect(i!)}
          href="#">
          {p!.name}
        </a>
      ))}
    </div>
  )
}

export default Suggestions
