// src/components/Spaces/Detail.tsx
import React from 'react'

import { Space } from '../../models'
import Display from '../Shared/Display'
import Refs from '../Shared/Refs'
import { Tab, Tabs } from '../Shared/RouteTabs'
import Theorems from './Theorems'
import Title from '../Shared/Title'
import Traits from './Traits'

export default React.memo(
  function Detail({ space }: { space: Space }) {
    return (
      <>
        <Title title={space.name} aliases={space.aliases} />
        <Display body={space.description} />
        <Tabs initial="theorems">
          <Tab eventKey="theorems" title="Theorems">
            <Theorems space={space} />
          </Tab>
          <Tab eventKey="properties" title="Properties">
            <Traits space={space} filter={true} />
          </Tab>
          <Tab eventKey="references" title="References">
            <Refs refs={space.refs} />
          </Tab>
        </Tabs>
      </>
    )
  }
)

// src/components/Spaces/Detail.svelte
<script lang="ts">
  import type { Space } from '../../models'
  import * as paths from '../../paths'
  import { References, Tab, Tabs, Tex, Title } from '../Shared'
  import Theorems from './Theorems.svelte'
  import Traits from './Traits.svelte'

  export let space: Space
  export let tab: 'theorems' | 'properties' | 'references' = 'theorems'
</script>

<Title {...space} />

<Tex body={space.description} />
<p />

<Tabs root={paths.space(space)} selected={tab} let:tabs>
  <Tab {tabs} path="theorems"><Theorems {space} /></Tab>
  <Tab {tabs} path="properties"><Traits {space} /></Tab>
  <Tab {tabs} path="references"><References refs={space.refs} /></Tab>
</Tabs>
