// src/components/Spaces/List.tsx
import React from 'react'
import { Link } from 'react-router-dom'

import { Space } from '../../models'
import paths from '../../paths'
import { Preview, Title } from '../Shared/Display'
import Id from '../Shared/Id'
import Table from '../Shared/Table'

const Header = () =>
  <tr>
    <Table.Header sort="uid">Id</Table.Header>
    <Table.Header sort="name">Name</Table.Header>
    <Table.Header>Description</Table.Header>
  </tr>

const Row = ({ item: space }: { item: Space }) =>
  <tr>
    <td>
      <Link to={paths.space(space)}>
        <Id value={space.uid} />
      </Link>
    </td>
    <td>
      <Title body={space.name} />
    </td>
    <td>
      <Preview body={space.description} />
    </td>
  </tr>

export default function ({ spaces }: { spaces: Space[] }) {
  return (
    <Table
      Header={Header}
      Row={Row}
      collection={spaces}
    />
  )
}

// src/components/Spaces/List.svelte
<script lang="ts">
  import type { Space } from '../../models'
  import { Id, Preview, Table, Tex } from '../Shared'

  export let spaces: Space[]
</script>

<Table collection={spaces} key={(s) => s.uid}>
  <tr slot="header" let:sort>
    <th on:click={sort('uid')}>Id</th>
    <th on:click={sort('name')}>Name</th>
    <th>Description</th>
  </tr>

  <tr slot="row" let:object={space}>
    <td><Id value={space.uid} /></td>
    <td><Tex body={space.name} /></td>
    <td><Preview body={space.description} /></td>
  </tr>
</Table>
