// src/components/Search/Examples.tsx
import * as React from 'react'

export interface Props extends React.HTMLProps<HTMLDivElement> {
  viewExample: (q: string) => void
}

class Examples extends React.Component<Props, {}> {
  examples() {
    return [
      {
        name: 'All Non-Metric Continua',
        q: 'compact + connected + t_2 + ~metrizable'
      },
      {
        name: 'A Common Non-Theorem',
        q: 'first countable + separable + ~second countable'
      }
      // {
      //   name: 'A Class of Examples by Name',
      //   q: ':plank'
      // },
      // {
      //   name: 'New Things to Prove',
      //   q: '?metacompact'
      // }
    ]
  }

  example({ name, q }: { name: string, q: string }) {
    const { viewExample } = this.props

    return (
      <article key={q}>
        <h5>{name}</h5>
        <a onClick={() => viewExample(q)}>
          <pre>{q}</pre>
        </a>
      </article>
    )
  }

  render() {
    return (
      <div className={this.props.className}>
        <p>Not sure where to start? Try one of the following searches</p>
        {this.examples().map(ex =>
          this.example(ex)
        )}
      </div>
    )
  }
}

export default Examples

// src/components/Search/Examples.svelte
<script lang="ts">
  export let select: (search: string) => void

  const examples = [
    {
      label: 'All Non-Metric Continua',
      search: 'compact + connected + t_2 + ~metrizable',
    },
    {
      label: 'A Common Non-Theorem',
      search: 'first countable + separable + ~second countable',
    },
  ]
</script>

<p><b>Not sure where to start?</b> Try one of the following searches:</p>
{#each examples as { label, search } (label)}
  <article>
    <h5>{label}</h5>
    <pre class="example" on:click={() => select(search)}>{search}</pre>
  </article>
{/each}
