// src/components/Search/Examples.jsx
import React, { PropTypes } from 'react'
import { connect } from 'react-redux'

import * as Q from '../../queries'

class Examples extends React.Component {
  examples() {
    return [
      {
        name: 'All Non-Metric Continua',
        q: 'compact + connected + ~metrizable'
      },
      {
        name: 'A Common Non-Theorem',
        q: 'first countable + separable + ~second countable'
      }
    ]
  }

  example(ex) {
    const { onSelect, parseFormula } = this.props
    const f = parseFormula(ex.q)

    return (
      <example key={ex.q}>
        <h5>{ex.name}</h5>
        <a onClick={() => onSelect(f)}>
          <pre>{ex.q}</pre>
        </a>
      </example>
    )
  }

  render() {
    return (
      <div>
        <p>Not sure where to start? Try one of the following searches</p>
        {this.examples().map(ex =>
          this.example(ex)
        )}
      </div>
    )
  }
}

Examples.propTypes = {
  onSelect: PropTypes.func.isRequired
}

export default connect(
  (state) => ({
    parseFormula: (q) => Q.parseFormula(state, q)
  })
)(Examples)

// src/components/Search/Examples.svelte
<script lang="ts">
  export let select: (search: string) => void

  const examples = [
    {
      label: 'All Non-Metric Continua',
      search: 'compact + connected + t_2 + ~metrizable',
    },
    {
      label: 'A Common Non-Theorem',
      search: 'first countable + separable + ~second countable',
    },
  ]
</script>

<p><b>Not sure where to start?</b> Try one of the following searches:</p>
{#each examples as { label, search } (label)}
  <article>
    <h5>{label}</h5>
    <pre class="example" on:click={() => select(search)}>{search}</pre>
  </article>
{/each}
