// src/App.tsx
import React, { useRef, useReducer } from 'react'
import { BrowserRouter as Router } from 'react-router-dom'

import './App.css'

import { boot, save } from './actions'
import * as Error from './errors'
import { useChange } from './hooks'
import { Dispatch, Reducer, reducer, initial } from './reducers'
import { status } from './models/Store/state'
import { Provider } from './models/Store/context'
import Nav from './components/Nav'
import Main from './components/Main'
import StatusBar from './components/StatusBar'
import { debounce } from './util'

const debouncedSave = debounce(save)

export default function App({
  errorHandler = Error.log(),
  startup = boot
}: {
  errorHandler?: Error.Handler
  startup?: (dispatch: Dispatch, errorHandler: Error.Handler) => Promise<void>
}) {
  const [store, dispatch] = useReducer<Reducer>(reducer, initial)

  useChange(store, debouncedSave)

  const booted = useRef(false)
  if (!booted.current) {
    booted.current = true
    startup(dispatch, errorHandler)
  }

  return (
    <Error.Provider value={errorHandler}>
      <Router>
        <Provider value={store}>
          <StatusBar status={status(store)} />
          <Nav />
          <Main dispatch={dispatch} />
        </Provider >
      </Router>
    </Error.Provider>
  )
}

// src/App.svelte
<script lang="ts">
  import { Router } from 'svelte-routing'
  import { onMount, setContext } from 'svelte'

  import { boot, save } from './actions'
  import { status } from './models/Store'
  import { reducer, initial } from './reducers'
  import type { Handler } from './errors'
  import { onChange } from './stores/onChange'
  import { reducerStore } from './stores/reducer'
  import { debounce } from './util'

  import Nav from './components/Nav.svelte'
  import Routes from './components/Routes.svelte'
  import StatusBar from './components/StatusBar.svelte'

  export let handler: Handler

  const state = reducerStore(reducer, initial)

  setContext('dispatch', state.dispatch)
  setContext('handler', handler)
  setContext('store', { subscribe: state.subscribe })

  onMount(() => {
    boot(state.dispatch, handler)
    onChange(state, debounce(save))
  })
</script>

<Router>
  <Nav branch={$state.remote.branch} />
  <div class="container">
    <Routes dispatch={state.dispatch} {handler} />
  </div>
</Router>

<StatusBar status={status($state)} />
