// src/components/Routes.svelte
<script lang="ts">
  import { Route } from 'svelte-routing'

  import Dev from './Dev/Dev.svelte'
  import Preview from './Dev/Preview.svelte'
  import Home from './Home.svelte'
  import NotFound from './Shared/NotFound.svelte'
  import Properties from './Properties/Properties.svelte'
  import Property from './Properties/Property.svelte'
  import Search from './Spaces/Search.svelte'
  import Space from './Spaces/Space.svelte'
  import Trait from './Traits/Trait.svelte'
  import Theorem from './Theorems/Theorem.svelte'
  import Theorems from './Theorems/Theorems.svelte'

  import type { Dispatch } from '../actions'
  import type { Handler } from '../errors'

  export let dispatch: Dispatch
  export let handler: Handler
</script>

<Route path="/spaces/:spaceId/properties/:propertyId" let:params>
  <Trait spaceId={params.spaceId} propertyId={params.propertyId} />
</Route>

<Route path="/spaces/:id/theorems" let:params>
  <Space id={params.id} tab="theorems" />
</Route>
<Route path="/spaces/:id/properties" let:params>
  <Space id={params.id} tab="properties" />
</Route>
<Route path="/spaces/:id/references" let:params>
  <Space id={params.id} tab="references" />
</Route>
<Route path="/spaces/:id" let:params>
  <Space id={params.id} />
</Route>
<Route path="/spaces" component={Search} />

<Route path="/properties/:id/theorems" let:params>
  <Property id={params.id} tab="theorems" />
</Route>
<Route path="/properties/:id/spaces" let:params>
  <Property id={params.id} tab="spaces" />
</Route>
<Route path="/properties/:id/references" let:params>
  <Property id={params.id} tab="references" />
</Route>
<Route path="/properties/:id" let:params>
  <Property id={params.id} />
</Route>
<Route path="/properties" component={Properties} />

<Route path="/theorems/:id/converse" let:params>
  <Theorem id={params.id} tab="converse" />
</Route>
<Route path="/theorems/:id/references" let:params>
  <Theorem id={params.id} tab="references" />
</Route>
<Route path="/theorems/:id" let:params>
  <Theorem id={params.id} />
</Route>
<Route path="/theorems" component={Theorems} />

<Route path="/dev/preview" component={Preview} />
<Route path="/dev" component={Dev} {dispatch} {handler} />
<Route path="/" component={Home} />

<Route path="*" component={NotFound} />

// src/routes.tsx
import * as React from 'react'

import { Route, Switch } from 'react-router'

import Home from './components/Home'
import Login from './components/Login'
import NotFound from './components/NotFound'
import Properties from './components/Property/List'
import Property from './components/Property'
import PropertyCreate from './components/Property/Create'
import Search from './components/Search'
import Space from './components/Space'
import SpaceCreate from './components/Space/Create'
import Theorem from './components/Theorem'
import TheoremCreate from './components/Theorem/Create'
import Theorems from './components/Theorem/List'
import User from './components/User'

const routes = (
  <Switch>
    <Route path="/" exact={true} component={Home} />

    <Route path="/login/:token" component={Login} />
    <Route path="/user" component={User} />

    <Route path="/spaces/new" component={SpaceCreate} />
    <Route path="/spaces/:spaceId" component={Space} />
    <Route path="/spaces" component={Search} />

    <Route path="/theorems/new" component={TheoremCreate} />
    <Route path="/theorems/:id" component={Theorem} />
    <Route path="/theorems" component={Theorems} />

    <Route path="/properties/new" component={PropertyCreate} />
    <Route path="/properties/:id" component={Property} />
    <Route path="/properties" component={Properties} />

    <Route component={NotFound} />
  </Switch>
)

export default routes
