// src/components/Shared/FormulaInput/Suggestions.tsx
import React from 'react'
import { ListGroup } from 'react-bootstrap'

import Inline from '../Inline'

export default function Suggestions({
  selected,
  suggestions
}: {
  selected: number | null,
  suggestions: readonly string[]
}) {
  return (
    <ListGroup>
      {suggestions.map((suggestion: string, index: number) =>
        <ListGroup.Item
          key={suggestion}
          active={index === selected}
        >
          <Inline body={suggestion} />
        </ListGroup.Item>
      )}
    </ListGroup>
  )
}

// src/components/Shared/Formula/Input/Suggestions.svelte
<script lang="ts">
  import type { Property } from '../../../../models'
  import Typeset from '../../Typeset.svelte'

  export let suggestions: Property[]
  export let selected: number | undefined
  export let onHover: (index: number) => void
  export let onClick: (index: number) => void
</script>

<ul class="list-group">
  {#each suggestions as property, i (property.id)}
    <li
      class="list-group-item {i === selected ? 'active' : ''}"
      on:mouseover={() => onHover(i)}
      on:click={() => onClick(i)}>
      <Typeset body={property.name} />
    </li>
  {/each}
</ul>
